### ISSUE TITLE
Puppet run gives me error

### ISSUE THREAD

**Issue by linuxcube** [smoeding/puppet-resolv_conf#1]
Without making any changes to the module, I am getting the following on a puppet run:

Error 500 on SERVER: Server Error: Could not find class resolv_conf for

**Comment by smoeding** [comment]
Unfortunately the error message is truncated and does not indicate what might go wrong in your case. Could you maybe show the code where you call the class and also post the full error message.

**Comment by smoeding** [comment]
Feedback timeout. No indication that there is actually anything wrong with the module.
